project:
  type: default
  output-dir: docs
  render:
    - reports/**/*.qmd
  resources:
    - .nojekyll

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    number-sections: true
    anchor-sections: true
    citations-hover: true
    footnotes-hover: true
    html-math-method: mathjax
    code-copy: true
    code-overflow: wrap

execute:
  freeze: auto
